### ISSUE TITLE
Using Default region (`US`)

### ISSUE THREAD

**Issue by alvpickmans** [petrbroz/vscode-forge-tools#1]
## Version
0.1.1

## Expected
See a list of all buckets from a particular Region (`US` or `EMEA`).

## Issue
Only buckets from the default `US` region are fetched.

## Proposal
Addition of a context menu to easily change the current region, or at least have it as a config setting.

**Comment by petrbroz** [comment]
Thanks for the heads up, @alvpickmans :+1:

**Comment by alvpickmans** [comment]
Awesome project btw, super useful when dealing with oss api :rocket:

**Comment by petrbroz** [comment]
Starting with version [0.3.1](https://github.com/petrbroz/vscode-forge-tools/releases/tag/v0.3.1) there's a new extension setting - `autodesk.forge.dataRegion` - specifying the data center region (`US` or `EMEA`) to be used when listing or creating OSS buckets.
