### ISSUE TITLE
Design Automation Tree issue

### ISSUE THREAD

**Issue by albisserAdrian** [petrbroz/vscode-forge-tools#10]
The design automation tree is not filtering the shared and owned app bundles and activities correctly. The owned section is always empty and the ones I create show up under shared App Bundles/Activities.

![image](https://user-images.githubusercontent.com/8847598/69581673-0878e400-102b-11ea-8935-f72c384e860b.png)

**Comment by petrbroz** [comment]
Thanks for reporting this @albisserAdrian! Let me take a look at what's going on there.

**Comment by petrbroz** [comment]
Looks like there was a problem when switching to another Forge environment - the client ID that the Design Automation tree uses to differentiate between owned vs shared records was not updated. Fixed now in develop branch, will be included in the next version: 1.4.6.
