### ISSUE TITLE
we hope to provide the function of resume from break point

### ISSUE THREAD

**Issue by davidyugang** [petrbroz/vscode-forge-tools#15]
when we use the tool to upload a huge model ,but we may not upload the model success beacause the broken of internet, so we hope to provide the function of resume from break point, by this way ,we do not need to restart the whole model, we think the function is very useful for everyone who use the tool.
thank you

**Comment by petrbroz** [comment]
Thank you for the comment. The upload *is* already resumable. If the uploading fails or if you cancel it before completion, you can then upload the same file under the same name, and it will automatically resume from the already uploaded part.

See this tweet: https://twitter.com/ipetrbroz/status/1142047862311796736

**Comment by petrbroz** [comment]
Since we haven't received any additional feedback, let us close the issue for now.
