### ISSUE TITLE
Upload file now asks to select a content-type after selecting the upload file

### ISSUE THREAD

**Issue by fpmalard** [petrbroz/vscode-forge-tools#25]
![Screen Shot 2020-06-10 at 13 47 10](https://user-images.githubusercontent.com/818592/84296336-400c3100-ab22-11ea-8fa7-5dcf62715843.jpg)

**Comment by petrbroz** [comment]
Yes, this was done on purpose, in case users want to specify a content type other than `application/octet-stream`. I'm not sure if there are any specific use cases (I know that, for example, certain content types are *not* allowed: https://forge.autodesk.com/blog/changes-oss-upload-and-download-content-type-header-security-improvement), though, so if you think this is not needed, perhaps we could hide this prompt behind a config flag?

**Comment by ofcdesk** [comment]
I see. I believe it could be an option once the default "octet-stream" would be the most used option thus allowing users to skip this step. If you think about the multiple files fashion, it would be even more boring to keep selecting this multiple times.
