### ISSUE TITLE
Download SVF doesn't set the output folder name as the bucket's object name

### ISSUE THREAD

**Issue by fpmalard** [petrbroz/vscode-forge-tools#27]
![Screen Shot 2020-06-10 at 14 00 16](https://user-images.githubusercontent.com/818592/84296701-c7f23b00-ab22-11ea-9654-e27ea00d6e3e.jpg)

**Comment by petrbroz** [comment]
Correct. That's because the OSS object name may contain unsafe characters. I'd be happy to change the naming of the folders to something else, as long as the names are guaranteed to be safe. Any suggestions?

**Comment by ofcdesk** [comment]
Indeed. Maybe you can validate the object name and then:
- If it does have all safe chars use its name as the target folder
- If it doesn't, use the Id the way it is now

**Comment by petrbroz** [comment]
I'm not sure if that's a good idea. I'd prefer some consistent approach where the naming would always behave the same way. Maybe we could just sanitize the name of the objects, but even then, it would be less intuitive to create an output **folder** called say `house.rvt`, and store the output in it...
