### ISSUE TITLE
Upload object to bucket on windows machine

### ISSUE THREAD

**Issue by LUC-ian** [petrbroz/vscode-forge-tools#3]
when trying to upload a file to a bucket, the extension adds a "/" in from of the path. 

<img width="339" alt="Capture" src="https://user-images.githubusercontent.com/7398467/64680547-4760ba00-d47e-11e9-8af1-bcd048fdc944.PNG">

**Comment by petrbroz** [comment]
Thank you for the bug report! :+1: The issue has been fixed in [v0.12.2](https://github.com/petrbroz/vscode-forge-tools/tree/v0.12.2), and the new version has just been published to marketplace.

**Comment by OMH2Share** [comment]
I have the same problem in version v.13.1
![Forge-tools](https://user-images.githubusercontent.com/35525080/64954684-a1022380-d886-11e9-8d21-015132f7ea14.png)

**Comment by petrbroz** [comment]
Make sure that you actually have version 0.13.1 installed and activated in your vscode. The badge in your screenshot is simply coming from the README file, saying that version 0.13.1 is now available in the marketplace, Make sure that this version appears next to the extension name in the sidebar:

![Výstřižek](https://user-images.githubusercontent.com/1470668/64955121-add34700-d887-11e9-94eb-80a789a7dae6.JPG)

**Comment by petrbroz** [comment]
Also, please note that on some platforms, vscode must be restarted before the new extension version is loaded.

**Comment by OMH2Share** [comment]
Thank you, I had 0.13.0 and after update to 0.13.1 it worked fine!

BR,
OleM Helgesen

**Comment by petrbroz** [comment]
Awesome!

My apologies for the confusion - the fix was already live in v0.12.2 but then it was accidentally reverted.
