### ISSUE TITLE
Webhook creation fails if Attributes field is empty 

### ISSUE THREAD

**Issue by adamenagy** [petrbroz/vscode-forge-tools#33]
If I leave the Attributes field empty I'll get the error: "Could not create webhook: Unexpected end of JSON input"
If I simply place {} there then it succeeds.

**Comment by petrbroz** [comment]
Jeez, you and your never ending complaints :P

**Comment by petrbroz** [comment]
It'll be fixed in the *SASP (Silence Adam Service Pack)* release.

**Comment by adamenagy** [comment]
🤣
