### ISSUE TITLE
Enable user to provide value for misc.workflow in "Translate Object (Custom)" command 

### ISSUE THREAD

**Issue by adamenagy** [petrbroz/vscode-forge-tools#34]
Enable user to set this part of the translation job body:
"misc": {
              "workflow": "my-workflow-id"
            }

See https://forge.autodesk.com/en/docs/webhooks/v1/tutorials/create-a-hook-model-derivative/

**Comment by petrbroz** [comment]
![giphy](https://media.giphy.com/media/Lry6jqqgMf3kk/giphy.gif)

**Comment by petrbroz** [comment]
Alright, this feature has been implemented and will be available in the next release.
