### ISSUE TITLE
Webhooks panel does not update after switching environment

### ISSUE THREAD

**Issue by adamenagy** [petrbroz/vscode-forge-tools#36]
Webhooks panel content does not update after switching environment and it does not have a refresh button either that I could click :(

**Comment by petrbroz** [comment]
Good catch, thanks! When switching environments, I forgot to refresh the `webhookTreeProvider`. Fixed: https://github.com/petrbroz/vscode-forge-tools/commit/93b08c6ced5be9ae105fa261f632be63d1977a95.

I also added a manual refresh button: https://github.com/petrbroz/vscode-forge-tools/commit/ba9b9eb2b4b0d3fee12ce432ff2502aa06cc1fd1.
