### ISSUE TITLE
Using an extensions beyond the proxy

### ISSUE THREAD

**Issue by CADBIMDeveloper** [petrbroz/vscode-forge-tools#39]
Hi, Petr,

I have a problem running your great VSCode extension beyond the proxy. It seems, it doesn't get the proxy configuration from the system settings, so I get:
![изображение](https://user-images.githubusercontent.com/14212214/99789238-4a9c0f00-2b33-11eb-823d-2446c63a063e.png)

In my C# code I fix such issues with this row:
`WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultNetworkCredentials;`

I don't have an experience on creating VSCode extensions, so I created this issue instead of pull request, sorry

**Comment by petrbroz** [comment]
Hi Alex, sorry for the troubles, and thanks for letting me know! I've never seen this issue before, but I'll definitely take a look.

**Comment by petrbroz** [comment]
Hi @CADBIMDeveloper, I'm starting off the year (btw Happy New Year!) with some cleanup work. Is the proxy still an issue, or can we close this?

**Comment by CADBIMDeveloper** [comment]
Hi @petrbroz , Happy New Year too!

I'm not working in the company I've faced this issue any more, so closing it.
