### ISSUE TITLE
Add multiple lines support for activity settings values

### ISSUE THREAD

**Issue by CADBIMDeveloper** [petrbroz/vscode-forge-tools#41]
Hi, Petr,

Add multiple lines support for activity settings values, please. 

Why? In DA for AutoCAD, the command should be defined like this:
`    "settings": {
        "script": {
            "value": "(command \"GenerateSectionViews\")\n"
        }
    }`

And it won't work without a new line at the end of the command.

Thank you!

**Comment by petrbroz** [comment]
Thank you Alexander, that's an interesting observation. It feels like something that should be addressed on the Design Automation side (I'll bring it up with the engineering team) but I'll make the text field support multiple lines anyways.
