### ISSUE TITLE
New activity tab and tab switch

### ISSUE THREAD

**Issue by CADBIMDeveloper** [petrbroz/vscode-forge-tools#42]
Hi, Petr,

"New activity" tab clears it's content if you switch to any other tab and then switch back again.

Steps to reproduce:
1) Start creating new activity. 
2) Enter any values to the fields
3) Switch to any other tab in VS Code
4) Switch back again

Thanks!

**Comment by petrbroz** [comment]
Thank you for the heads up! I've updated the webviews so that they always retain their context (in https://github.com/petrbroz/vscode-forge-tools/commit/42a58adc361f8c05810e8650a46c193e111006b9). The fix will be available with the next release.
