### ISSUE TITLE
Using the "rename object" menu item will break the link between the object and any derivatives

### ISSUE THREAD

**Issue by garethem** [petrbroz/vscode-forge-tools#47]
if you are tempted to rename an object to make it more meaningful after loading, there is a "rename object" selection available on the menu.
Using this will lose the connection with any derivatives and seems to prevent doing actions like "translate object" on the renamed object.  
The only solution is to reload the object from scratch

**Comment by petrbroz** [comment]
Thank you for bringing this up Gareth.

There is no close connection between designs in the Data Management service and their derivatives in the Model Derivative service. Derivatives are simply stored under the base64-encoded ID of their (original) design in OSS. When you rename the object, the derivatives are not lost or removed, it's just that the vscode extension (just like any other typical Forge application) starts querying the MD service with new ID for which there are no derivatives yet.

Having said that, I agree that this behavior may be a bit surprising, and I'll add a popup dialog with a warning.
