### ISSUE TITLE
SVF2 Support

### ISSUE THREAD

**Issue by florolf1** [petrbroz/vscode-forge-tools#51]
Hey,

I just found out that all derivative functions only work for models in svf format.
Downlod derivatives as svf/glft/otg/f2d for models in svf2 format does not word.

Is it planned to add support for svf2?

**Comment by petrbroz** [comment]
Hi there!

That's correct. When you convert your designs into the `svf2` format, the Model Derivative service will only create `svf2` outputs, meaning that there will be no `svf(1)` or `f2d` available for downloading. As for the glTF download, the glTF files are actually **converted** from `svf(1)`, so it's the same situation.

The SVF2 format is a bit more difficult to download (it's not just a bunch of files you can download) but I'll see if we can support it, too.

**Comment by florolf1** [comment]
Thank you for the feedback.
For my pipeline, i need to convert the `svf` files to `gltf` in order to continue working with them on mobile devices (AR/VR).
However, some Revit models are so large (1GB +) that I have switched completely to `svf2` format which has improved the viewer performance immensely.
But as already mentioned, I need the possibility to convert the models into `gltf.`

If you can be helped with the conversion support, I would be willing to work with you.

Alternatively, I think it is also possible to convert model into SVF and SVF2 at the same time? Is that correct?

**Comment by petrbroz** [comment]
Thanks Florian! If you're willing to look at the code and submit a PR I'd be happy to look at it.

I can't find it anywhere in the official Forge docs now but I believe that you can **only specify one** output format (SVF or SVF2), not both :( One workaround (a bit annoying in my opinion) would be to translate your model into SVF(1), download it as a glTF, and then start another translation, this time into SVF2...

**Comment by petrbroz** [comment]
In order to make the glTF download work for cases, we would basically have to support direct SVF2-to-glTF translation. Note that the forge-convert-utils library (used by the vscode extension for the glTF conversion) does already include an **experimental** support for SVF2 (called "OTG" in the past) but that code would still need some work.

**Comment by petrbroz** [comment]
After discussing the OTG/SVF2 topic internally, a decision was made not to support manual downloading and parsing of these formats. There were various technical, legal, and business reasons for this. I will remove the OTG option from the VSCode extension.
