### ISSUE TITLE
when i download svf ,i face a problem :Could not download SVF: Request path contains unescaped characters

### ISSUE THREAD

**Issue by SHAO-QII** [petrbroz/vscode-forge-tools#54]
Could not download SVF: Request path contains unescaped characters
why i can not download that?

**Comment by SHAO-QII** [comment]
![image](https://user-images.githubusercontent.com/82205417/136144693-e728ef8d-1572-48cd-9316-fcebe6355948.png)

**Comment by haoerloveyou** [comment]
Hi bro I meet the same question and I wanna share my rvt please give me an email address tks

**Comment by haoerloveyou** [comment]
or mail me haoerloveyou@me.com then I rely the rvt model to you :p

**Comment by xiaodongliang** [comment]
Hi @petrbroz , I made a demo model which can reproduce this issue.  When the name of any Revit **View** has Chinese characters, the issue can happen. If name of Sheet has Chinese char, it is not reproducible. I believe it is not only Chinese char can reproduce. https://myshare.autodesk.com/:u:/g/personal/xiaodong_liang_autodesk_com/EepkrfATW55IjaTeYOxhYokBAiIBDwzyCXIBCkwpCRgwww?e=CaerZo
Thank you!
<img width="393" alt="Screen Shot 2021-11-04 at 11 28 22 AM" src="https://user-images.githubusercontent.com/5087461/140253249-39f45856-534f-4073-b80b-94c3f16c56af.png">

**Comment by petrbroz** [comment]
Awesome, thank you @xiaodongliang! Let me look at that.

**Comment by petrbroz** [comment]
The issue has been resolved and the fix will be available in version 2.3.3.
