### ISSUE TITLE
Let me specify the receiver value for aliases (both app bundle and activity)

### ISSUE THREAD

**Issue by adamenagy** [petrbroz/vscode-forge-tools#56]

**Comment by petrbroz** [comment]
In version 2.3.2, when creating/updating Design Automation aliases (for app bundles and activities), you can now specify a `receiver` as well. For now this is still done through a simple input prompt but I'm planning on creating a form-like input for DA aliases (similar to how you create activities or work items) in the future.

Also, you can now right-click a specific alias and choose `View Alias Details` to bring up a new tab with the alias information.

**Comment by adamenagy** [comment]
👏 🍾  🎉
