### ISSUE TITLE
create activity buttons in panel are not working

### ISSUE THREAD

**Issue by jeroenVerdonschot** [petrbroz/vscode-forge-tools#57]
Hi,

Great extension. But I run into a problem. When I try to create a new activity, none of the buttons are working in the New Activity screen. 
I reinstalled the extension. The problem persists.

I have got the latest version of vscode:
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

please help. I really want to use this extension :)

**Comment by petrbroz** [comment]
Thank you for the heads up! I just tried creating a new activity on my end, and both buttons seem to be working fine. My setup is:

```
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

Are you saying that in your case _none_ of the buttons are working? Even the "Cancel" button cannot be used to close the window, or the "magic wand" button cannot be used to auto-populate the command line field?

**Comment by petrbroz** [comment]
Also, could you try the [webview developer tools](https://dzhavat.github.io/2020/11/12/easy-way-to-debug-a-webview-in-a-vscode-extension.html), and see if there are any errors in the New Activity webpage?

Note that in the dev tools you'll need to switch to the corresponding iframe context:
<img width="1792" alt="Screen Shot 2021-11-04 at 3 15 03 PM" src="https://user-images.githubusercontent.com/1470668/140329828-18054ce6-d32a-48ca-861d-a9f4105e001b.png">

**Comment by jeroenVerdonschot** [comment]
Hi Petr,

Sorry for my delayed reply.

I made a screenshot of the developer screen.

![vscode](https://user-images.githubusercontent.com/6209211/142151950-2a29ff6e-4580-4bcc-9fc4-0a4ad2998bdc.png)

None of the buttons are working. Also the cancel button.

I hope the screenshot helps.

thanks!

**Comment by petrbroz** [comment]
Thank you @jeroenVerdonschot, it looks like the vscode webview isn't able to fetch jQuery (we use Bootstrap & jQuery for all the UI). Could this be some sort of firewall issue on your side perhaps? Can you access https://code.jquery.com/jquery-3.3.1.slim.min.js directly?

**Comment by petrbroz** [comment]
Btw. I'm planning to reimplement all the UI using [VSCode WebView UI Toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit) which would remove the Bootstrap/jQuery dependency, and hopefully resolve the issue for you.

**Comment by petrbroz** [comment]
Hi @jeroenVerdonschot, I have just finished a major overhaul of the UI, moving from Bootstrap/jQuery/Pug to https://github.com/microsoft/vscode-webview-ui-toolkit. Let me close this issue, and if you run into other problems, please let me know.
