### ISSUE TITLE
Filter Hubs & Derivatives View

### ISSUE THREAD

**Issue by watcherkb** [petrbroz/vscode-forge-tools#58]
Hi Petr, is it possible to filter/search Hubs by name? And is it possible to sort all Hubs?

**Comment by petrbroz** [comment]
VSCode provides a simple but nice [search/filter](https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree) functionality that might get you what you want:

![vscode-search-filter](https://user-images.githubusercontent.com/1470668/147916214-9ad75deb-3c3f-488d-8226-296c29ae3b22.gif)

As for sorting, that is not supported at the moment but we could consider that a new feature request.

**Comment by watcherkb** [comment]
thank you for pointing me to the serach functionality. That was new to me.
