### ISSUE TITLE
I'd like at easy way to get a base64 URN for an item

### ISSUE THREAD

**Issue by KeanW** [petrbroz/vscode-forge-tools#6]
Right now I use base64encode.org, but having en encoded URN directly in the property list would be awesome!

**Comment by petrbroz** [comment]
Good to see you @KeanW!

I agree. You can get the URN today by right-clicking an OSS object, choosing _View Object Manifest_, and copying the URN at the very top (see the screenshot below), but I've been thinking about adding _Copy URN to Clipboard_ directly to the right-click menu. Does that sound good?

![image](https://user-images.githubusercontent.com/1470668/67949818-b63dd200-fbe8-11e9-8751-a71955c865e1.png)

**Comment by KeanW** [comment]
Now that I know the way, I can live with that. The right-click menu would be easier, but then it’s pretty busy already.

Kean

**Comment by petrbroz** [comment]
Yeah, I'm waiting for vscode API to add [support for nested menus](https://github.com/microsoft/vscode/issues/9827)...

I think I'll add the additional menu item anyway, since it's a pretty common operation.

**Comment by KeanW** [comment]
﻿Perfect. Thanks again for making this great toolset!

**Comment by petrbroz** [comment]
This feature has been implemented in https://github.com/petrbroz/vscode-forge-tools/tree/v1.4.1.
