### ISSUE TITLE
download NWD as SVF not working

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/vscode-forge-tools#66]
type tags have changed from 

**Autodesk.CloudPlatform.Geometry** 

to 
​
**Autodesk.CloudPlatform.Viewpoint** 
and 
**Autodesk.CloudPlatform.NamedItemTree**

without this check, no geometry is downloaded

**Comment by petrbroz** [comment]
Is the structure of the data in these new resource types same as in `Autodesk.CloudPlatform.Geometry`? If so, I'll update [forge-convert-utils](https://github.com/petrbroz/forge-convert-utils) to process the new resource types as well.

**Comment by petrbroz** [comment]
Btw I just checked the forge-convert-utils code, and I'm not finding `Autodesk.CloudPlatform.Geometry` anywhere in there. What kind of resource are you referring to exactly? Did you mean `Autodesk.CloudPlatform.GeometryMetadataList`?

**Comment by petrbroz** [comment]
Also, I just tried converting one of my sample NWDs and it got processed without issues. So I'm guessing it might only be reproducible with newer versions of Navisworks designs. Could you share one with me please?

**Comment by wallabyway** [comment]
It was a  breaking change to MD api a while ago.  The change was reverted.  Closing
