### ISSUE TITLE
Add Direct-3S download/upload support

### ISSUE THREAD

**Issue by yiskang** [petrbroz/vscode-forge-tools#82]
Some DM-related functions seem targeting to the deprecated endpoints in the dependent package, which need to be migrated.

**Comment by petrbroz** [comment]
Thanks @yiskang. Just like with https://github.com/petrbroz/vscode-forge-tools/issues/83, I'm planning to migrate to the official Node.js SDK (incl. the new direct S3 upload/download) as soon as it's ready. Do you think it's ok to wait for the SDK, or do we need to add our own implementation until the SDK is ready?

**Comment by yiskang** [comment]
@petrbroz Happy New Year! No worry. it's okay to wait for the new SDK. There was someone asked me about this, so I created this issue for tracking.
