### ISSUE TITLE
OAuth v2 API migration

### ISSUE THREAD

**Issue by yiskang** [petrbroz/vscode-forge-tools#83]
OAuth v1 API will be retired on April 30, 2024, according to https://aps.autodesk.com/blog/important-update-authentication-v1-deprecation-extended-april-30th-2024-act-now, but some OAuth-related functions seem targeting to V1.

**Comment by petrbroz** [comment]
Thank you @yiskang, I'm planning to migrate this extension to use the official [APS SDK for Node.js](https://github.com/autodesk-platform-services/aps-sdk-node/tree/main) as soon as it's ready.

**Comment by yiskang** [comment]
@petrbroz Happy New Year! No worry. it's okay to wait for the new SDK. There was someone asked me about this, so I created this issue for tracking.

BTW, currently, [APS SDK for Node.js](https://github.com/autodesk-platform-services/aps-sdk-node) seems not to have an SDK wrapper for authentication API. Probably, the engineering team is still working on it.

**Comment by petrbroz** [comment]
Correct. SDKs for Auth and OSS are still a work-in-progress. Once they are done, we can proceed with the migration.

**Comment by petrbroz** [comment]
There's still some missing pieces in the official SDK (for example, no Design Automation, and no way to specify custom base URLs), so for now I've just updated this project to the latest version of the [unofficial SDK](https://github.com/petrbroz/aps-sdk-node) that uses Auth v2. I will track the migration to the [official SDK](https://github.com/autodesk-platform-services/aps-sdk-node) in a separate GitHub issue.
