### ISSUE TITLE
Support for APAC region

### ISSUE THREAD

**Issue by visualphyzx** [petrbroz/vscode-forge-tools#91]
Please can you add the support for APAC region. Thank you!

**Comment by kioter1** [comment]
Hi, when I download the svf packet, there is only one output.svf file downloaded, I can't find any other files. May I know what I should do?

**Comment by petrbroz** [comment]
An experimental support for APAC region has been added in 2.7.1. Please note that as of now the region is only honoured by _some_ APIs (for example, Data Management).
